Librinfo\UserBundle\Entity\Group:
    type:  entity
    id:
        id:
            type: guid
            generator:  { strategy: UUID }
    fields:
        name:
            type: string
            nullable: false
        roles:
            type: array
    manyToMany:
        users:
            mappedBy: groups
            targetEntity: Librinfo\UserBundle\Entity\User
