default: # see available parameters with command : app/console debug:container --parameters | grep fos_user
    fos_user.firewall_name:
        default: N/A
        replace: main
    fos_user.model.group.class:
        default: Librinfo\DoctrineBundle\Entity\GenericEntity
        replace: Librinfo\UserBundle\Entity\Group
    fos_user.model.user.class:
        default: Librinfo\DoctrineBundle\Entity\GenericEntity
        replace: Librinfo\UserBundle\Entity\User
    fos_user.resetting.email.from_email:
        default:
            - webmaster@example.com: webmaster
        replace:
            - support@libre-informatique.fr: support
    fos_user.storage:
        default: N/A
        replace: orm