default:
    sonata.user.admin.group.entity:
        default: Application\Sonata\UserBundle\Entity\Group
        replace: Librinfo\UserBundle\Entity\Group
    sonata.user.admin.user.entity:
        default: Application\Sonata\UserBundle\Entity\User
        replace: Librinfo\UserBundle\Entity\User