parameters:
    librinfo:
        FOS\UserBundle\Entity\User:
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [id, salt, confirmationToken, passwordRequestedAt, credentialsExpired, credentialsExpireAt, expiresAt]
                add:
                    _options:
                        fieldsOrder: [username, name, firstname]
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                _copy: Sonata\AdminBundle\Datagrid\ListMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            username: ~
                            name: ~
                            firstname: ~
                            email: ~
                        form_group_details:
                            enabled: ~
                            locked: ~
                            expired: ~
                            expiresAt: ~
                    form_group_security:
                        form_group_password:
                            plainPassword:
                                type: repeated
                                required: false
                                translation_domain: FOSUserBundle
                        form_group_roles:
                            roles: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper

        Librinfo\UserBundle\Entity\Traits\Traceable:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_specifics:
                        form_group_misc:
                            createdBy:
                                type: entity
                                class: Librinfo\UserBundle\Entity\User
                                read_only: true
                                disabled: true
                                required: false
                            updatedBy:
                                type: entity
                                class: Librinfo\UserBundle\Entity\User
                                read_only: true
                                disabled: true
                                required: false

        Librinfo\UserBundle\Entity\Traits\Ownable:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_specifics:
                        form_group_misc:
                            owner:
                                type: entity
                                class: Librinfo\UserBundle\Entity\User
                                required: false
