parameters:
    librinfo:
        FOS\UserBundle\Entity\User:
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [id, salt, confirmationToken, passwordRequestedAt, credentialsExpired, credentialsExpireAt, expiresAt]
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                  username: ~
        Librinfo\UserBundle\Entity\Traits\Traceable:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    Specifics:
                        Misc:
                            createdBy:
                                type: entity
                                class: Librinfo\UserBundle\Entity\User
                                read_only: true
                                disabled: true
                                required: false
                            updatedBy:
                                type: entity
                                class: Librinfo\UserBundle\Entity\User
                                read_only: true
                                disabled: true
                                required: false
