parameters:
    librinfo:
        Librinfo\UserBundle\Entity\Traits\Traceable:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    Specifics:
                        Misc:
                            createdBy:
                                type: entity
                                class: Librinfo\UserBundle\Entity\User
                                read_only: true
                                disabled: true
                                required: false
                            updatedBy:
                                type: entity
                                class: Librinfo\UserBundle\Entity\User
                                read_only: true
                                disabled: true
                                required: false
