#librinfo_user_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: LibrinfoUserBundle:Default:index }

sonata_user_register:
    resource: "@LibrinfoUserBundle/Resources/config/registration_routes.xml"
    prefix: /register