parameters:
    librinfo.user_bundle.user.class: %fos_user.model.user.class%

services:
    app.user:
        class: Librinfo\UserBundle\Admin\UserAdminConcrete
        arguments: [~, Librinfo\UserBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Application Management, label: Users}
        calls:
            - [setSecurityPasswordEncoder,['@security.password_encoder']]
    app.group:
        class: Librinfo\UserBundle\Admin\GroupAdminConcrete
        arguments: [~, Librinfo\UserBundle\Entity\Group, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Application Management, label: Groups}

# Service that manage Traceable doctrine mapping and behavior

    librinfo.user_entities.listener.traceable:
        class: Librinfo\UserBundle\EventListener\TraceableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setTokenStorage, [@security.token_storage]]
            - [setUserClass, [%librinfo.user_bundle.user.class%]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]

