parameters:
    librinfo.user_bundle.user.class: %fos_user.model.user.class%

# Create User and Group admins
services:
    app.user:
        class: Librinfo\UserBundle\Admin\UserAdmin
        arguments: [~, Librinfo\UserBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Application Management
                label: librinfo.user.user_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [setSecurityPasswordEncoder,['@security.password_encoder']]
    app.group:
        class: Librinfo\UserBundle\Admin\GroupAdmin
        arguments: [~, Librinfo\UserBundle\Entity\Group, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Application Management
                label: librinfo.user.group_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
# Authentication    
    librinfo_user.authenticate:
        class: Librinfo\UserBundle\Services\Authenticate
        arguments: [@security.token_storage]
        calls:
            - [setUserManager, ['@fos_user.user_manager']]

# Service that manages Traceable doctrine mapping and behavior
    librinfo_user.listener.traceable:
        class: Librinfo\UserBundle\EventListener\TraceableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setTokenStorage, [@security.token_storage]]
            - [setUserClass, [%librinfo.user_bundle.user.class%]]
            - [setClassAnalyser, [Blast\CoreBundle\Tools\Reflection\ClassAnalyzer]]

# Service that manages Ownable doctrine mapping
    librinfo_user.listener.ownable:
        class: Librinfo\UserBundle\EventListener\OwnableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setTokenStorage, [@security.token_storage]]
            - [setUserClass, [%librinfo.user_bundle.user.class%]]
            - [setClassAnalyser, [Blast\CoreBundle\Tools\Reflection\ClassAnalyzer]]

