services:
    app.user:
        class: Librinfo\UserBundle\Admin\UserAdminConcrete
        arguments: [~, Librinfo\UserBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Application Management, label: Users}
        calls:
            - [setSecurityPasswordEncoder,['@security.password_encoder']]
    app.group:
        class: Librinfo\UserBundle\Admin\GroupAdminConcrete
        arguments: [~, Librinfo\UserBundle\Entity\Group, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Application Management, label: Groups}